### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by SpatialJ** [deeplight77/NugetPackageRestore#3]
trying to install the package i get:
PM> Install-Package NugetPackageRestore
Installing 'NugetPackageRestore 1.0.3'.
Successfully installed 'NugetPackageRestore 1.0.3'.
Adding 'NugetPackageRestore 1.0.3' to zuers_geo_gp_tools.
Uninstalling 'NugetPackageRestore 1.0.3'.
Successfully uninstalled 'NugetPackageRestore 1.0.3'.
Install failed. Rolling back...
Install-Package : Could not install package 'NugetPackageRestore 1.0.3'. You are trying to install this package into a project that targets 
'.NETFramework,Version=v3.5', but the package does not contain any assembly references or content files that are compatible with that 
framework. For more information, contact the package author.
At line:1 char:1
- Install-Package NugetPackageRestore
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

trying to install the package via the ui fails, since i cannot find it there using the search

**Comment by deeplight77** [comment]
This package targets .Net Framework version 4, if you could upgrade your project to version 4 the you will be able to install the package.

**Comment by SpatialJ** [comment]
Ah ok. Unfortunately i cannot upgrade since that library works with 3.5
only. Are there major differences between 3.5 and 4 from ths msbuild
perspective, or would it be easy to recompile the task for 3.5?

Thanks!
